# Basic CPU test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the basic test
run_or1ksim "basic" \
    [list "report(0xffff0012);" \
          "report(0x12352af7);" \
          "report(0x7ffffffe);" \
          "report(0xffffa5a7);" \
          "report(0x000fffff);" \
          "report(0x00002800);" \
          "report(0x00000009);" \
          "report(0xdeaddead);" \
          "!exit(0)"] \
    "" "basic/basic"
