# Cache CPU test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the cache test
run_or1ksim "cache" \
    [list "report(0x00000000);" \
	 "report(0xdeaddead);" \
	 "report(0x00000001);" \
	 "report(0xdeaddead);" \
	 "report(0x00000002);" \
	 "report(0xdeaddead);" \
	 "report(0x00000003);" \
	 "report(0x00000004);" \
	 "report(0xdeaddead);" \
	 "report(0xdeaddead);" \
	 "exit(0)"] \
    "" "cache/cache"
