# DMA test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the DMA test
run_or1ksim "dmatest" \
    [list "!Starting DMA test" \
	  "!  Simple DMA: report(0x00000001);" \
	  "Passed" \
	  "!  Chunks DMA: report(0x00000006);" \
	  "Passed" \
	  "!  List DMA: report(0x0000000a);" \
	  "Passed" \
	  "!Ending DMA test" \
          "!report(0xdeaddead);" \
	  "!exit(0)"] \
    "" "dmatest/dmatest"
