# fpee.exp. Floating point exception DejaGNU tests

# Copyright (C) 2023 OpenRISC Developers

# Contributor Stafford Horne <shorne@gmail.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the floating point test
run_or1ksim "fpee" \
    [list "Switching to User Mode" \
          "Enabling FPU Exceptions" \
	  "Exceptions enabled, now DIV 3.14 / 0" \
	  "Got fpe: " \
	  "report(0x7f800000);" \
	  "report(0x00000801);" \
	  "One more, now MUL 3.14 * MAX" \
	  "Got fpe: " \
	  "report(0x7f800000);" \
	  "report(0x00000109);" \
	  "exit(0)"] \
    "fp.cfg" "fpee/fpee"
