# inst-set-test.exp. Tests of ORBIS32 instruction set

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the l.lws test
run_or1ksim "lws-test"                            \
    [list "!l.lws"                                \
          "   l.lws r4,0(r5): r4=0xdeadbeef:  OK" \
          "   l.lws r4,0(r5): r4=0x00000000:  OK" \
          "   l.lws r4,0(r5): r4=0x7fffffff:  OK" \
          "   l.lws r4,0(r5): r4=0x80000000:  OK" \
          "   l.lws r4,0(r5): r4=0xffffffff:  OK" \
          "   l.lws r4,0(r5): r4=0x00000000:  OK" \
          "   l.lws r4,0(r5): r4=0x7fffffff:  OK" \
          "   l.lws r4,0(r5): r4=0x80000000:  OK" \
          "   l.lws r4,0(r5): r4=0xffffffff:  OK" \
          "   l.lws r4,0(r5): r4=0xdeadbeef:  OK" \
          "   l.lws r4,0(r5): r4=0x00000000:  OK" \
          "   l.lws r4,0(r5): r4=0x7fffffff:  OK" \
          "   l.lws r4,0(r5): r4=0x80000000:  OK" \
          "!Test completed"                       \
          "!report(0xdeaddead);"                  \
	  "!exit(0)"]                             \
    "inst-set-test.cfg" "inst-set-test/is-lws-test"
