# mem-test.exp. Simple memory test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the simple memory test.
run_or1ksim "mem-test"          \
    [list "report(0x12345678);" \
	 "report(0x00001234);" \
	 "report(0x00005678);" \
	 "report(0x00000012);" \
	 "report(0x00000034);" \
	 "report(0x00000056);" \
	 "report(0x00000078);" \
	 "report(0xdeaddead);" \
	 "report(0x5678dead);" \
	 "report(0x56781234);" \
	 "report(0xdd781234);" \
	 "report(0xddcc1234);" \
	 "report(0xddccbb34);" \
	 "report(0xddccbbaa);" \
	 "report(0xda25e544);" \
	 "report(0xdeaddead);" \
	 "!exit(0)"] \
    "" "mem-test/mem-test"
