# MMU test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the Ethernet test
run_or1ksim "mmu"                                \
    [list "ea = 0017bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0017e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0027bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0027e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0047bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0047e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0087bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0087e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0107bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0107e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0207bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0207e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0407bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0407e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0807bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 0807e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 1007bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 1007e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 2007bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 2007e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 4007bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 4007e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 8007bffc set = 61 way = 0"       \
          "tlbtr = 0017b3c0 dtlb_val = 000003c0" \
          "ea = 8007e000 set = 63 way = 0"       \
          "tlbtr = 0017e3c0 dtlb_val = 000003c0" \
          "ea = 0027c000 set = 62 way = 0"       \
          "tlbtr = 0017c3c0 dtlb_val = 000003c0" \
          "ea = 0027c000 set = 62 way = 0"       \
          "tlbtr = 0017c3c0 dtlb_val = 000003c0" \
          "ea = 0017c000 set = 62 way = 0"       \
          "ea = 0017c000 set = 62 way = 0"       \
          "ea = 0017c000 set = 62 way = 0"       \
          "ea = 0017c000 set = 62 way = 0"       \
          "ea = 0017bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0017e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0027bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0027e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0047bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0047e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0087bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0087e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0107bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0107e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0207bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0207e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0407bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0407e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0807bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 0807e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 1007bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 1007e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 2007bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 2007e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 4007bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 4007e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 8007bff8 set = 61 way = 0"       \
          "ta = 0017bff8"                        \
          "ea = 8007e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0027e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0027e000 set = 63 way = 0"       \
          "ta = 0017e000"                        \
          "ea = 0017c000 set = 62 way = 0"       \
          "ea = 0017c000 set = 62 way = 0"       \
          "report(0xdeaddead);"                  \
	  "exit(0)"]                             \
    "mmu.cfg" "mmu/mmu"
