# MMU test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------

# Allow up to 30 seconds to run this
set old_timeout $timeout
set timeout 30


# Run the MMU test
run_or1ksim "mmu"                                \
    [list "DTLB translation tests OK" \
	 "DTLB match tests OK" \
	 "DTLB valid bit tests OK" \
	 "DTLB permission bit tests OK" \
	 "ITLB translation tests OK" \
	 "ITLB match tests OK" \
	 "ITLB valid bit tests OK" \
	 "ITLB permission tests OK" \
	 "Tests completed" \
	 "report(0xdeaddead);" \
	 "report(0x8000000d);" \
	 "exit(0)"] \
    "mmu.cfg" "mmu/mmu"
