# cbasic.exp. Test of multiplication using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the multiplication test
run_or1ksim "mul"                       \
    [list "00000000"                    \
          "cac28a17"                    \
          "a6312f33, expected a6312f33" \
          "059b8f08, expected 059b8f08" \
          "00000000, expected 00000000" \
          "!report(0xdeaddead);"         \
          "!Test succesful."             \
	  "!exit(0)"]                    \
    "" "mul/mul"
