# int-test.exp. Interrupt controller test using DejaGNU under automake

# Copyright (C) 2010 Embecosm Limited

# Contributor Jeremy Bennett <jeremy.bennett@embecosm.com>

# This file is part of OpenRISC 1000 Architectural Simulator.

# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 3 of the License, or (at your option)
# any later version.

# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
# more details.

# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <http:#www.gnu.org/licenses/>.  */

# -----------------------------------------------------------------------------
# This code is commented throughout for use with Doxygen.
# -----------------------------------------------------------------------------


# Run the Interrupt controller test
run_or1ksim "int-test"          \
    [list "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x00000628);" \
          "report(0x00000000);" \
          "report(0x0000062c);" \
          "report(0x00000004);" \
          "report(0x0000062c);" \
          "report(0x00000004);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000630);" \
          "report(0x00000008);" \
          "report(0x00000634);" \
          "report(0x0000000c);" \
          "report(0x00000634);" \
          "report(0x0000000c);" \
          "report(0x00000638);" \
          "report(0x00000010);" \
          "report(0x00000638);" \
          "report(0x00000010);" \
          "report(0x00000638);" \
          "report(0x00000010);" \
          "report(0x00000638);" \
          "report(0x00000010);" \
          "report(0x0000063c);" \
          "report(0x00000014);" \
          "report(0x0000063c);" \
          "report(0x00000014);" \
          "report(0x00000640);" \
          "report(0x00000018);" \
          "report(0x00000640);" \
          "report(0x00000018);" \
          "report(0x00000640);" \
          "report(0x00000018);" \
          "report(0x00000640);" \
          "report(0x00000018);" \
          "report(0x0000064c);" \
          "report(0x00000024);" \
          "report(0x00008203);" \
          "report(0x0000064c);" \
          "report(0x00000024);" \
          "report(0x00008203);" \
          "report(0x0000064c);" \
          "report(0x00000024);" \
          "report(0x00008203);" \
          "report(0x0000064c);" \
          "report(0x00000024);" \
          "report(0x00008203);" \
          "report(0x00000650);" \
          "report(0x00000028);" \
          "report(0x00008003);" \
          "report(0x00000650);" \
          "report(0x00000028);" \
          "report(0x00008003);" \
          "report(0x00000650);" \
          "report(0x00000028);" \
          "report(0x00008003);" \
          "report(0x00000650);" \
          "report(0x00000028);" \
          "report(0x00008003);" \
          "report(0x00000658);" \
          "report(0x00000030);" \
          "report(0x00000658);" \
          "report(0x00000030);" \
          "report(0x0000065c);" \
          "report(0x00000034);" \
          "report(0x0000065c);" \
          "report(0x00000034);" \
          "report(0x00000660);" \
          "report(0x00000038);" \
          "report(0xdeaddead);" \
	  "exit(0)"]            \
    "" "int-test/int-test"
